rm experiments/base_model/last_weights/*
rm experiments/base_model/best_weights/*
rm experiments/base_model/train_summaries/*
rm experiments/base_model/vali_summaries/*
rm experiments/base_model/train.log
rm experiments/base_model/evaluate.log
rm experiments/base_model/metrics_eval_best_weights.json
rm experiments/base_model/metrics_eval_last_weights.json
rm experiments/base_model/metrics_test_best_weights.json
rm *.out
